### PR TITLE
linux-raspberrypi-5.4: revert 1 commit from upstream to fix lttng-mod…

### PR DESCRIPTION
**Pull request by shr-project**
…ules build

* fixes:
  lttng-modules/2.12.2-r0/lttng-modules-2.12.2/probes/../probes/lttng-tracepoint-event-impl.h:131:6: error: conflicting types for 'trace_writeback_queue_io'

* fixes:
  https://github.com/agherzan/meta-raspberrypi/pull/721

### CODE REVIEW

**Review by agherzan — DISMISSED** [review]
Nice one. Have you given it a spin?

**Comment by shr-project** [comment]
> Nice one. Have you given it a spin?

Yes, it fixes the build for me.

The issue is that writeback_queue_io was updated in lttng-modules in:
https://github.com/lttng/lttng-modules/commit/817e02f9e256b8f2cbb9e3125eb061757b83bd4a
which isn't included in 2.12.2 version currently in oe-core and even if it is, then it checks for kernel version 5.9 and won't work with this commit backported from 5.9 to rpi-5.4.y.

I'll update the commit with this info, so that it isn't only in the PR.

**Comment by agherzan** [comment]
Cheers @shr-project

**Review by agherzan — APPROVED** [review]
