### PR TITLE
libcamera-apps: fix build with libcamera-0.2.0

### PR DESCRIPTION
**Pull request by shr-project**
* it's failing to build since the upgrade in: https://git.openembedded.org/meta-openembedded/commit/?id=711c6fbce39df685225bca081c5f42bae2de658b

* fixes ../git/core/libcamera_app.cpp: In member function 'void LibcameraApp::ConfigureViewfinder()': ../git/core/libcamera_app.cpp:327:25: error: 'class libcamera::CameraConfiguration' has no member named 'transform'
    327 |         configuration_->transform = options_->transform;
        |                         ^~~~~~~~~

* be aware that the repository and libraries were removed in 1.4.0 version with: https://github.com/raspberrypi/rpicam-apps/commit/0ca9f41fea587458b5b447c2b079328056452252 but I'll leave that change to someone actually using this, I was just fixing the build issue found in world builds

* tweak FILES to package library symlink without "lib" prefix to fix: ERROR: libcamera-apps-1.4.2+git-r0 do_package: QA Issue: libcamera-apps: Files/directories were installed but not shipped in any package: /usr/lib/rpicam_app.so Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install. libcamera-apps: 1 installed and not shipped files. [installed-vs-shipped]

### CODE REVIEW

**Review by agherzan — APPROVED** [review]

**Comment by agherzan** [comment]
Thanks! Merged to master.
